In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
print("OK")

OK

In [2]:
Sales = r"E:\برتفوليو كامل\Portfolio Data Analysis\python\New folder (3)\Data File Before Cleaning\sales.xlsx"

In [3]:
sales=pd.ExcelFile(Sales)

In [4]:
sales.sheet_names

['Customers', 'Products', 'Orders', 'OrderItems']

In [5]:
customers= pd.read_excel(sales, sheet_name='Customers')
orders=pd.read_excel(sales, sheet_name='Orders')
products= pd.read_excel(sales, sheet_name='Products')
orderitems=pd.read_excel(sales, sheet_name='OrderItems')

In [6]:
customers.head(4)

,CustomerID,CustomerName,City,Email,Phone,SignupDate
0,CUST_00001,جلاء آل معيض,NaN,mhntwlyn@example.com,+1-976-787-4764x3804,2025-06-23
1,CUST_00002,الدكتور ساجي آل خضير,NaN,al-mydmasd@example.org,(533)735-4211,2023-11-03
2,CUST_00003,محمود آل بن ظافر,NaN,pal-bn-zfr@example.net,001-224-833-9326x6946,2024-03-22
3,CUST_00004,راغب آل علي,NaN,allhjr@example.com,001-606-638-9572x025,2026-07-20

In [7]:
customers.tail(10)

,CustomerID,CustomerName,City,Email,Phone,SignupDate
30490,CUST_24673,ربى آل صفوان,الدمام,bd-lswlmlmhydb@example.org,(779)353-9776x8588,2025-04-12
30491,CUST_13721,نجدت العجلان,جدة,bn-ldnrshdy@example.org,687-690-1501x846,2026-07-15
30492,CUST_17847,خاشعة الجفالي,الرياض,bw-dwwdsjd@example.net,700-793-0949,2024-10-10
30493,CUST_03383,الدكتور عمران بقشان,الرياض,olmhydb@example.net,(776)588-9715x2103,2025-04-22
30494,CUST_09846,السيدة هيام آل رفيع,جدة,mslmal-rfy@example.net,invalid_phone,2025-07-10
30495,CUST_18833,بلند آل حسين,الرياض,btsm54@example.org,+1-264-899-2427,2026-02-14
30496,CUST_19341,روبين آل بن ظافر,الرياض,zyd52@example.org,3084915356,2026-04-25
30497,CUST_07340,الآنسة ياسمين الحكير,الرياض,dysmlhjr@example.org,479.781.2636,2025-10-26
30498,CUST_14369,فهمي المغاولة,مكة,xmhn@example.org,+1-553-963-3764x8113,2024-06-30
30499,CUST_14660,بلند حنبولي,الدمام,bws88@example.net,806.424.9399x5317,2024-07-16

In [8]:
c_clean= customers.copy()

In [9]:
c_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30500 entries, 0 to 30499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    30500 non-null  object
 1   CustomerName  30500 non-null  object
 2   City          29867 non-null  object
 3   Email         28945 non-null  object
 4   Phone         30500 non-null  object
 5   SignupDate    30500 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 1.4+ MB

In [10]:
c_clean["City"].isna().sum()

np.int64(633)

In [11]:
c_clean["City"]=c_clean["City"].fillna("Unknown")

In [12]:
c_clean["Phone"].astype("string").replace(r'\D', '',regex=True)

0          197678747643804
1               5337354211
2        00122483393266946
3         0016066389572025
4           56474498293820
               ...
30495          12648992427
30496           3084915356
30497           4797812636
30498      155396337648113
30499       80642493995317
Name: Phone, Length: 30500, dtype: string

In [13]:
c_clean["Phone"]=c_clean["Phone"].astype("string").replace(r'\D', '',regex=True)

In [14]:
c_clean["Email"].isna().sum()

np.int64(1555)

In [15]:
c_clean["Email"]= c_clean["Email"].fillna("Not Available")

In [16]:
(c_clean == "").sum()

CustomerID         0
CustomerName       0
City               0
Email              0
Phone           2501
SignupDate         0
dtype: Int64

In [17]:
c_clean["Phone"]=(
    c_clean["Phone"].str.strip().replace('','Not Available')
)

In [18]:
c_clean["CustomerID"].duplicated().sum()

np.int64(500)

In [19]:
c_clean["CustomerID"].nunique()

30000

In [20]:
c_clean.drop_duplicates(inplace=True)

In [21]:
c_clean["City"].unique()

array(['Unknown', 'الرياض', 'جدة', 'الدمام', 'مكة', 'المدينة', 'Jeddah',
       'Riyadh', 'الريّاض'], dtype=object)

In [22]:
c_clean["City"]=c_clean["City"].astype("string").str.strip()

In [23]:
city_mapping={
    'Jeddah': 'جدة',
    'Riyadh': 'الرياض',
    'الريّاض' : 'الرياض'
}

c_clean["City"] = (
    c_clean["City"].replace(city_mapping)\
)

In [24]:
products.head(4)

   ProductID     ProductName        Category    Price
0  PROD_0001  ملابس - منتج 1  مستحضرات تجميل  1456.45
1  PROD_0002   أثاث - منتج 2           أغذية  3442.32
2  PROD_0003  ملابس - منتج 3      إلكترونيات  3064.23
3  PROD_0004   أثاث - منتج 4           ملابس  2756.65

In [25]:
products.tail(10)

      ProductID                 ProductName    Category    Price
4990  PROD_4991      إلكترونيات - منتج 4991  إلكترونيات  2961.23
4991  PROD_4992           أغذية - منتج 4992       ملابس  3244.13
4992  PROD_4993      إلكترونيات - منتج 4993       ملابس  3539.35
4993  PROD_4994           ملابس - منتج 4994       أغذية  2879.41
4994  PROD_4995           أغذية - منتج 4995       ملابس   862.10
4995  PROD_4996            أثاث - منتج 4996  إلكترونيات    71.14
4996  PROD_4997           أغذية - منتج 4997        أثاث  3824.39
4997  PROD_4998      إلكترونيات - منتج 4998       ملابس  1962.74
4998  PROD_4999            أثاث - منتج 4999       ملابس  1206.26
4999  PROD_5000  مستحضرات تجميل - منتج 5000       ملابس   622.07

In [26]:
p_clean=products.copy()

In [27]:
p_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    5000 non-null   object
 1   ProductName  5000 non-null   object
 2   Category     5000 non-null   object
 3   Price        4989 non-null   float64
dtypes: float64(1), object(3)
memory usage: 156.4+ KB

In [28]:
p_clean["Price"].isna().sum()

np.int64(11)

In [29]:
p_clean["Price"]=(
    p_clean["Price"].fillna(p_clean.groupby("Category")["Price"].transform("mean"))
)

In [30]:
p_clean.isnull().any().any()

np.False_

In [31]:
(p_clean=='').sum()

ProductID      0
ProductName    0
Category       0
Price          0
dtype: int64

In [32]:
p_clean["ProductID"].duplicated().sum()

np.int64(0)

In [33]:
orders.head(4)

,OrderID,CustomerID,OrderDate,SalesChannel,OrderStatus,ShippingDate
0,ORD_000001,CUST_10584,2026-05-16,Store,Review_Needed,2026-05-18
1,ORD_000002,CUST_04879,2025-09-07,online,Completed,2025-09-02
2,ORD_000003,CUST_07818,2025-11-16,متجر إلكتروني,Returned,2025-11-19
3,ORD_000004,CUST_09923,2025-09-02,online,Cancelled,2025-09-09

In [34]:
orders.tail(10)

,OrderID,CustomerID,OrderDate,SalesChannel,OrderStatus,ShippingDate
119990,ORD_119991,CUST_13278,2026-07-22,تطبيق,Completed,2026-07-19
119991,ORD_119992,CUST_05373,2025-09-13,تطبيق,Returned,2025-09-20
119992,ORD_119993,CUST_11422,2025-03-07,App,Review_Needed,2025-03-14
119993,ORD_119994,CUST_25940,2025-10-03,App,Pending,2025-10-09
119994,ORD_119995,CUST_24149,2025-03-25,online,Returned,2025-03-25
119995,ORD_119996,CUST_27795,2026-09-22,App,Cancelled,2026-09-30
119996,ORD_119997,CUST_19586,2025-11-01,تطبيق,Cancelled,2025-11-06
119997,ORD_119998,CUST_19410,2025-02-11,متجر إلكتروني,Pending,2025-02-20
119998,ORD_119999,CUST_17414,2025-08-20,App,Pending,2025-08-15
119999,ORD_120000,CUST_08896,2025-08-10,Store,Pending,2025-08-14

In [35]:
o_clean= orders.copy()

In [36]:
o_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   OrderID       120000 non-null  object
 1   CustomerID    120000 non-null  object
 2   OrderDate     120000 non-null  datetime64[ns]
 3   SalesChannel  120000 non-null  object
 4   OrderStatus   120000 non-null  object
 5   ShippingDate  120000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), object(4)
memory usage: 5.5+ MB

In [37]:
(o_clean=='').sum()

OrderID         0
CustomerID      0
OrderDate       0
SalesChannel    0
OrderStatus     0
ShippingDate    0
dtype: int64

In [38]:
o_clean["SalesChannel"].unique()

array(['Store', 'online', 'متجر إلكتروني', 'App', 'تطبيق', 'Online'],
      dtype=object)

In [39]:
channel_mapping={
    'متجر إلكتروني':'Online',
    'تطبيق':'App'
}

o_clean["SalesChannel"]=o_clean["SalesChannel"].str.strip().str.title().replace(channel_mapping)

In [40]:
invalid_date=o_clean[o_clean["ShippingDate"] < o_clean["OrderDate"]]
len(invalid_date)

39667

In [41]:
o_clean= o_clean[~(o_clean["ShippingDate"] < o_clean["OrderDate"])]

In [42]:
o_clean.isnull().sum()

OrderID         0
CustomerID      0
OrderDate       0
SalesChannel    0
OrderStatus     0
ShippingDate    0
dtype: int64

In [43]:
(o_clean=='').sum()

OrderID         0
CustomerID      0
OrderDate       0
SalesChannel    0
OrderStatus     0
ShippingDate    0
dtype: int64

In [44]:
o_clean["OrderStatus"].unique()

array(['Review_Needed', 'Returned', 'Cancelled', 'Completed', 'Pending'],
      dtype=object)

In [45]:
orderitems.head(4)

         ItemID     OrderID  ProductID  Quantity  Discount CustomerID_Fake
0  ITEM_0000001  ORD_021172  PROD_3252         0      0.22         UNKNOWN
1  ITEM_0000002  ORD_119652  PROD_2928         1      0.14         UNKNOWN
2  ITEM_0000003  ORD_054806  PROD_3994        -1      0.16         UNKNOWN
3  ITEM_0000004  ORD_108740  PROD_1372       100      0.23         UNKNOWN

In [46]:
orderitems.tail(10)

,ItemID,OrderID,ProductID,Quantity,Discount,CustomerID_Fake
359990,ITEM_0359991,ORD_074823,PROD_4310,3,0.24,NaN
359991,ITEM_0359992,ORD_111481,PROD_4862,0,0.08,NaN
359992,ITEM_0359993,ORD_107696,PROD_3008,5,0.14,NaN
359993,ITEM_0359994,ORD_019488,PROD_1474,5,0.21,NaN
359994,ITEM_0359995,ORD_038515,PROD_3312,4,0.85,NaN
359995,ITEM_0359996,ORD_063973,PROD_4532,2,0.15,NaN
359996,ITEM_0359997,ORD_060059,PROD_1964,5,0.14,NaN
359997,ITEM_0359998,ORD_100601,PROD_2153,5,0.10,NaN
359998,ITEM_0359999,ORD_015505,PROD_4164,0,0.15,NaN
359999,ITEM_0360000,ORD_055204,PROD_4962,100,0.04,NaN

In [47]:
oi_clean=orderitems.copy()

In [48]:
oi_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360000 entries, 0 to 359999
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ItemID           360000 non-null  object
 1   OrderID          360000 non-null  object
 2   ProductID        360000 non-null  object
 3   Quantity         360000 non-null  int64
 4   Discount         360000 non-null  float64
 5   CustomerID_Fake  1001 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 16.5+ MB

In [49]:
(oi_clean=='').sum()

ItemID             0
OrderID            0
ProductID          0
Quantity           0
Discount           0
CustomerID_Fake    0
dtype: int64

In [50]:
oi_clean = oi_clean.replace(r'^\s*$', np.nan, regex=True)

In [51]:
oi_clean.isnull().sum()

ItemID                  0
OrderID                 0
ProductID               0
Quantity                0
Discount                0
CustomerID_Fake    358999
dtype: int64

In [52]:
invalid_qtys = oi_clean[oi_clean['Quantity'] <= 0]

In [53]:
len(invalid_qtys)

90241

In [54]:
oi_clean = oi_clean[oi_clean['Quantity'] > 0]

In [55]:
invalid_discounts = oi_clean[oi_clean['Discount'] < 0]

print("عدد الصفوف ذات الخصومات السالبة:", len(invalid_discounts))

عدد الصفوف ذات الخصومات السالبة: 0

In [56]:
oi_clean.loc[oi_clean['Discount'] < 0, 'Discount'] = 0

In [57]:
c_clean.to_csv('customers.csv', index=False, encoding='utf-8-sig')

In [58]:
o_clean.to_csv('orders.csv', index=False, encoding='utf-8-sig')

In [59]:
p_clean.to_csv('products.csv', index=False, encoding='utf-8-sig')

In [60]:
oi_clean.to_csv('orderitems.csv', index=False, encoding='utf-8-sig')